package com.openstack_4j.network.model;

import java.io.Serializable;

public class Employee implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employeeID
     *
     * @mbggenerated
     */
    private Integer employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employeeName
     *
     * @mbggenerated
     */
    private String employeename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.departmentID
     *
     * @mbggenerated
     */
    private Integer departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employeeID
     *
     * @return the value of employee.employeeID
     *
     * @mbggenerated
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employeeID
     *
     * @param employeeid the value for employee.employeeID
     *
     * @mbggenerated
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employeeName
     *
     * @return the value of employee.employeeName
     *
     * @mbggenerated
     */
    public String getEmployeename() {
        return employeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employeeName
     *
     * @param employeename the value for employee.employeeName
     *
     * @mbggenerated
     */
    public void setEmployeename(String employeename) {
        this.employeename = employeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.departmentID
     *
     * @return the value of employee.departmentID
     *
     * @mbggenerated
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.departmentID
     *
     * @param departmentid the value for employee.departmentID
     *
     * @mbggenerated
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }
}